name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile: [rails_4.0.0.gemfile, rails_5.0.0.gemfile, rails_5.2.3.gemfile, rails_6.0.0.gemfile, rails_7.0.0.gemfile, rails_master.gemfile]
        ruby_version: [2.4.x, 2.5.x, 2.6.x, 2.7.x, 3.0.x]
        exclude:
          - gemfile: rails_master.gemfile
            ruby_version: 2.7.x
          - gemfile: rails_7.0.0.gemfile
            ruby_version: 2.7.x
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Update rubygems when testing with Ruby 2.4.x
      if: startsWith(matrix.ruby_version, '2.4')
      run: |
        gem update --system --no-document
    - name: Before build
      run: |
        sudo apt-get install libsqlite3-dev
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: b94c73e21e64da03cde9403f237f1dd1927d97a6f188b99dd651ebf9051ebe35
    - name: Build and test
      run: |
        gem install bundler:1.17.3
        bundle _1.17.3_ update
        bundle _1.17.3_ install --gemfile spec/gemfiles/${{ matrix.gemfile }} --jobs 4 --retry 3
        bundle _1.17.3_ exec rake code_analysis
        bundle _1.17.3_ exec rspec
    - name: Report to CodeClimate
      run: |
        ./cc-test-reporter after-build --exit-code 0
      env:
        CC_TEST_REPORTER_ID: b94c73e21e64da03cde9403f237f1dd1927d97a6f188b99dd651ebf9051ebe35
