name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.5.x, 2.6.x, 2.7.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Download CodeClimate reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: 33a23b18b12b65ab41da2e9b664dd576d2cc03a04da268473108570fc72cfa62
    - name: Build and test
      run: |
        gem install bundler:1.17.3
        bundle update
        bundle install --jobs 4 --retry 3
        bundle exec rake code_analysis
        bundle exec rspec
    - name: Report to CodeClimate
      run: |
        ./cc-test-reporter after-build --exit-code 0
      env:
        CC_TEST_REPORTER_ID: 33a23b18b12b65ab41da2e9b664dd576d2cc03a04da268473108570fc72cfa62
